[package]
name = "voice-waveform-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.3"
serde = { version = "1.0.194", features = ["serde_derive"] }
sha2 = "0.10.8"
tokio = { version = "1.35.1", features = ["full"] }
url = "2.5.0"
voice-shared = { path = "../voice-shared" }
