[package]
name = "voice-shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
axum = "0.7.5"
url = "2.5.2"
tokio = { version = "1.40.0", features = ["rt", "macros", "fs"] }
tower-http = { version = "0.5.2", features = ["cors", "compression-br"] }
async-trait = "0.1.82"
