[package]
name = "builder"
version = "0.0.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
toml = "0.8.8"

[lib]
name = "builder"
path = "src/lib.rs"

[[bin]]
name = "builder"
path = "src/main.rs"
