[workspace]
resolver = "2"

members = [
	"voice-file-upload",
	"voice-waveform-gen",
	"voice-shared",
	"voice-analyzer",
	"builder",
]

# faster build times
# [profile.release.package.voice-analyzer]
# opt-level = 0
# debug = false
# 
[profile.release]
strip = true