FROM rust:1.75 as chef
	RUN cargo install cargo-chef
	RUN rustup target add x86_64-unknown-linux-musl
	RUN apt update && \
		apt install -y musl musl-tools ffmpeg mold imagemagick && \
		rm -rf /var/lib/apt/lists/*

	WORKDIR /build
	COPY . .

FROM chef as planner
	WORKDIR /build
	RUN cargo chef prepare --recipe-path recipe.json

FROM planner as builder
	ENV RUSTFLAGS="-C target-feature=+crt-static -C link-arg=-fuse-ld=mold"
	RUN cargo chef cook --release --target x86_64-unknown-linux-musl --recipe-path recipe.json
	COPY . .
	RUN cargo build --release --target x86_64-unknown-linux-musl

FROM scratch as voice-base
	COPY --from=builder /build/voice/target/x86_64-unknown-linux-musl/release/voice-analyzer /voice-analyzer
	COPY --from=builder /build/voice/target/x86_64-unknown-linux-musl/release/voice-file-upload /voice-file-upload
	COPY --from=builder /build/voice/target/x86_64-unknown-linux-musl/release/voice-waveform-gen /voice-waveform-gen
	COPY --from=builder /usr/bin/ffmpeg /usr/bin/ffmpeg
	COPY --from=builder /usr/bin/magick /usr/bin/magick

# Targets
FROM voice-base as voice-analyzer
	CMD ["/voice-analyzer"]

FROM voice-base as voice-file-upload
	CMD ["/voice-file-upload"]

FROM voice-base as voice-waveform-gen
	CMD ["/voice-waveform-gen"]

# Prevent building without --target specified
FROM scratch as dummy
