FROM rust:1.81-bookworm as chef
	RUN cargo install cargo-chef
	RUN rustup target add x86_64-unknown-linux-gnu
	RUN apt update && \
		apt install -y mold && \
		rm -rf /var/lib/apt/lists/*

	WORKDIR /build
	COPY . .

FROM chef as planner
	WORKDIR /build
	RUN cargo chef prepare --recipe-path recipe.json

FROM chef as builder
	COPY --from=planner /build/recipe.json recipe.json
	ENV RUSTFLAGS="-C target-feature=+crt-static -C link-arg=-fuse-ld=mold"
	RUN cargo chef cook --release --target x86_64-unknown-linux-gnu --recipe-path recipe.json
	COPY . .
	RUN cargo build --release --target x86_64-unknown-linux-gnu

# Targets
# I'm too lazy to check which ones need ffmpeg and magick and which don't.
FROM alpine:edge as voice-analyzer
	RUN apk update && apk add --no-cache ffmpeg imagemagick
	COPY --from=builder /build/target/x86_64-unknown-linux-gnu/release/voice-analyzer /voice-analyzer
	# COPY --from=chef /usr/bin/ffmpeg /usr/bin/ffmpeg
	CMD ["/voice-analyzer"]

FROM alpine:edge as voice-waveform-gen
	RUN apk update && apk add --no-cache ffmpeg imagemagick
	COPY --from=builder /build/target/x86_64-unknown-linux-gnu/release/voice-waveform-gen /voice-waveform-gen
	CMD ["/voice-waveform-gen"]

# Prevent building without --target specified
FROM scratch as dummy
